# Generated by Django 4.2.23 on 2025-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requesttype_remove_client_active_client_company_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
