# Generated by Django 4.2.23 on 2025-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_is_active_alter_clientrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
