# Generated by Django 4.2.23 on 2025-06-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clientrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
